update to 0.10
2gis/native-sdk-ios-demo pull request #19
Opened 2021-04-09 04:37 UTC by lagner

2021-04-09 12:43 UTC, aapng requested changes

2021-04-09 12:43 UTC, aapng commented on docs/ru/changelog.md
> +- *Ломающее изменение:* обновили класс GeoRect
```suggestion
- cоздание пользовательского слоя распознавания жестов теперь возможно при инициализации карты, см. `gestureViewFactory` у `MapOptions`
- *Ломающее изменение:* изменили устройство типов, связанных с картой. Теперь карту нужно создавать вызовом `Container.makeMapFactory(options:) -> IMapFactory`. Из него доступен контролер карты — `map`, вид карты `mapView` и прочие вещи.
- *Ломающее изменение:* обновили класс GeoRect
```

2021-04-09 12:43 UTC, aapng commented on docs/ru/changelog.md
> +- добавили метод takeSnapshot для получения последнего отрисованного кадра в картинку
```suggestion
- добавили инструмент для получения последнего отрисованного кадра карты в виде изображения — `IMapFactory.snapshotter.makeImage()`
```

2021-04-09 12:43 UTC, aapng commented on docs/ru/changelog.md
> +- *Ломающее изменение:* мы изменили формат работы с подписками на изменения свойств. Раньше такие поля как camera.position имели тип StatefulChannel. Для того чтобы получать уведомления об изменениях
```suggestion
- *Ломающее изменение:* мы изменили формат работы с подписками на изменения свойств. Раньше такие поля как `Map.camera.position` имели тип `StatefulChannel`. Прежде получали уведомления об изменениях значений свойств с помощью `camera.position.sink(receiveValue:)`, а текущее значение через `camera.position.value`. Такой API вызывал трудности и был менее эффективен, поэтому в новой версии, например, `camera.position` это просто свойство типа `CameraPosition`; а `camera.positionChannel` — `StatefulChannel<CameraPosition>. Это изменение в силе для всех свойств, ранее имевших тип `StatefulChannel`.
```

2021-04-09 12:43 UTC, aapng commented on docs/ru/changelog.md
> +## v0.10
```suggestion
## v0.10.1
```

2021-04-15 10:43 UTC, lagner commented on docs/ru/changelog.md
> +## v0.10
Не, тут идея такая что 
```
## 0.10
```
пишется основная версия и ее изменения, а потом 
```
### 0.10.1
```
описание патч версий со списком исправленных багов

2021-04-15 11:14 UTC, aapng approved these changes

2021-04-15 11:14 UTC, merged