Update master to v0.12
2gis/native-sdk-ios-demo pull request #24
Opened 2021-04-22 07:27 UTC by maxal9999

2021-04-23 15:48 UTC, lagner approved these changes

2021-04-26 07:02 UTC, aapng requested changes

2021-04-26 07:02 UTC, aapng commented on docs/ru/changelog.md
> +- Исправлена проблема с маркерами, при которой они группировались на разных масштабах.
Непонятно, в чём была проблема. Нужно переформулировать.

2021-04-26 07:02 UTC, aapng commented on docs/ru/changelog.md
> +- Установлено минимальное значение zoom-левела равное 2.
"Zoom-левел" — плохая формулировка для публичного текста. Нужно сказать нормально. Например, на 2-м масштабном уровне.

Если есть желание быть предельно точным, то укажи API, на которые это повлияло.

2021-04-26 07:18 UTC, maxal9999 commented on docs/ru/changelog.md
> +- Исправлена проблема с маркерами, при которой они группировались на разных масштабах.
А что на твой взгляд тут выглядит непонятным? Была проблема, при которой маркеры группировались в один - то есть одни перекрывали другие.

2021-04-26 07:21 UTC, maxal9999 commented on docs/ru/changelog.md
> +- Установлено минимальное значение zoom-левела равное 2.
Ну вот для меня Zoom-левел звучит понятнее, чем второй масштабный уровень. Наши же пользователи - это также разработчики. И большинство понимают, что такое уровень зума.

2021-04-26 07:21 UTC, maxal9999 commented on docs/ru/changelog.md
> +- Исправлен механизм сбора статистики BSS.
Поправил.

2021-04-28 06:43 UTC, ok-gurov approved these changes

2021-04-28 15:10 UTC, merged