Update to v0.13.0
2gis/native-sdk-ios-demo pull request #29
Opened 2021-04-30 20:52 UTC by maxal9999

2021-05-01 04:54 UTC, t-artikov commented on docs/en/changelog.md
> +- Исправлено промаргивание карты черным цветом при ее создании.
Это исправление только для Android делали. На iOS либо проблема осталась, либо ее не было.

2021-05-01 04:58 UTC, maxal9999 commented on docs/en/changelog.md
> +- Исправлено промаргивание карты черным цветом при ее создании.
Хм, мне казалось, что изменение в плюсах было. Понял, неправильно подумал. Скинь в слак Тикет, по которому это исправлено было - я на iOS проверю.

2021-05-01 05:01 UTC, maxal9999 commented on docs/en/changelog.md
> +- Исправлено промаргивание карты черным цветом при ее создании.
done

2021-05-04 06:28 UTC, aapng requested changes

2021-05-04 21:02 UTC, maxal9999 commented on docs/en/changelog.md
> +- Функции для создания объектов заменены на конструкторы `createMapObjectManager` -> `MapObjectManager`, `Geometry.createPoint` -> `PointGeometry` и т.д.
В принципе, со всем согласился и поправил. Спасибо.

2021-05-05 01:20 UTC, aapng approved these changes

2021-05-05 08:40 UTC, merged