[SDK-798] Написать пример по добавлению своих стилей и их смене
2gis/native-sdk-ios-demo pull request #38
Opened 2021-05-27 13:44 UTC by ok-gurov

Перед вливанием нужно будет заменить ссылку на доку редактора стилей.

2021-05-28 03:32 UTC, ok-gurov commented on docs/ru/examples.md
> +Методы [loadFile](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadFile) и [loadResource](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadResource) получают ссылку на файл пакета с
```suggestion
Методы [loadFile](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadFile) и [loadResource](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadResource) получают ссылку на файл пакета стилей (см. [Экспорт стиля](/ru/mapgl/styles/overview#nav-lvl1--Введение) // TODO: Заменить ссылку на корректную после [DOKA-139]), и возвращают объект [Future](/ru/ios/native/maps/reference/Future), который можно использовать для получения экземпляра загруженного стиля.
```

2021-05-28 07:46 UTC, aapng requested changes

2021-05-28 07:46 UTC, aapng commented on app/Views/DemoPages/MapTheme/MapThemeDemoView.swift
> +				.frame(width: 40, height: 40, alignment: .center)
У SwiftUI есть трудности с форматированием. Короче говоря, выравнивай точки во ViewBuilder-ах по линии изначального объекта, без дополнительного отступа.

Пример — Button в этой же функции тремя строками выше.

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +Методы [loadFile](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadFile) и [loadResource](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadResource) получают ссылку на файл пакета с
```suggestion
Методы [loadFile](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadFile) и [loadResource](/ru/ios/native/maps/reference/IStyleFactory#nav-lvl1--loadResource) получают ссылку на файл пакета стилей (см. [Экспорт стиля](/ru/mapgl/styles/overview#nav-lvl1--Введение) (TODO: Заменить ссылку на корректную после [DOKA-139]). Возвращают [Future](/ru/ios/native/maps/reference/Future) с отложенно загружаемым экземпляром стиля.
```

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +// Настройки карты
Нужно единообразно ставить или не ставить точки в конце предложений во всём файле. Лучше ставить.

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +		// Устанавливаем загруженный стиль
```suggestion
		// Меняем активный стиль карты.
```

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +// Загружаем новый стиль карты
```suggestion
// Загружаем новый стиль карты. Можно использовать только файловые URL (file://).
```

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +Пример создание карты с заданной темой:
```suggestion
Пример создания карты с заданной темой:
```

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +При создании фабрики объектов карты (см. [makeStyleFactory()](/ru/ios/native/maps/reference/Container#nav-lvl1--makeStyleFactory)) настроить тему можно, установив параметр `appearance` в первоначальн
Тут имеется в виду makeMapFactory — нужно исправить текст и ссылку.

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +При создании фабрики объектов карты (см. [makeStyleFactory()](/ru/ios/native/maps/reference/Container#nav-lvl1--makeStyleFactory)) настроить тему можно, установив параметр `appearance` в первоначальн
В целом грузная формулировка, читается труднее нужного. Предлагаю такую формулу:
> Тему стиля карты можно указать при создании новой карты или в уже существующей.
> При создании карты тема указывается с помощью свойства appearance объекта MapOptions, передаваемого в makeMapFactory.
> В уже существующей карте тема меняется с помощью свойства IMapView.appearance.

2021-05-28 07:46 UTC, aapng commented on docs/ru/examples.md
> +// Слой карты
Следующие несколько строк до конца блока дублируются ниже. Нужно удалить лишнее.

2021-06-04 06:42 UTC, aapng approved these changes

2021-06-04 06:42 UTC, aapng commented on app/Views/DemoPages/MapTheme/MapThemeDemoView.swift
> +				buttons: buttons)
```suggestion
				buttons: buttons
			)
```

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
> +// Иконка на основе PNG-данных (быстрее).
```suggestion
// Иконка на основе PNG-данных (быстрее, чем из UIImage).
```

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
> +		// Координаты для выреза внутри многоугольника.
```suggestion
		// Координаты выреза внутри многоугольника.
```

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
>  let connection = map.camera.state().sink { state in
С тех пор уже нужно использовать не `state()`, а `stateChannel`. Нужно проверить инструкцию, но менять не в этом PR.

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
> +При создании карты тема указывается с помощью свойства appearance объекта [MapOptions](/en/ios/native/maps/reference/MapOptions#nav-lvl1--appearance), передаваемого в [makeMapFactory](/en/ios/native/
```suggestion
При создании карты тема указывается с помощью свойства `appearance` объекта [MapOptions](/en/ios/native/maps/reference/MapOptions#nav-lvl1--appearance), передаваемого в [makeMapFactory](/en/ios/native/maps/reference/Container#nav-lvl1--makeMapFactory).
```

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
> +В уже существующей карте тема меняется с помощью свойства IMapView.appearance.
```suggestion
В уже существующей карте тема меняется с помощью свойства `IMapView.appearance`.
```

2021-06-04 06:42 UTC, aapng commented on docs/en/examples.md
> +	options.appearance = .automatic(light: "night", dark: "day")
```suggestion
	options.appearance = .automatic(light: lightTheme, dark: darkTheme)
```

2021-06-06 13:25 UTC, ok-gurov commented on app/Views/DemoPages/MapTheme/MapThemeDemoView.swift
> +			self.viewFactory.makeMapView(appearance: self.viewModel.currentTheme.mapAppearance)
Вызывается updateView, если не менялся `.id()` у карты.

2021-06-06 16:03 UTC, ok-gurov commented on app/Views/DemoPages/CustomMapStyle/CustomMapStyleDemoView.swift
> +			.frame(width: 40, height: 40, alignment: .center)
Добавил фабричный метод

2021-06-07 08:14 UTC, maxal9999 commented on app/Views/DemoPages/MapTheme/MapThemeDemoViewModel.swift
> +					return "Тема стиля по умолчанию"
А какая тема стиля по умолчанию?

2021-06-07 08:15 UTC, maxal9999 approved these changes

2021-06-07 08:22 UTC, merged